/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Venda.java
 *
 * Created on 30/09/2010, 19:48:15
 */
package clientewebservice;

import clientewebservice.resources.service.IncluirCredito;

/**
 *
 * @author leandro
 */
public class Venda extends javax.swing.JFrame {

    /** Creates new form Venda */
    public Venda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCliente = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox();
        jLProdutos = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLQtd = new javax.swing.JLabel();
        jTFQtd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVenda = new javax.swing.JTable();
        jBInserir = new javax.swing.JButton();
        jLTotal = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JTextField();
        jBGravar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(clientewebservice.ClienteWebServiceApp.class).getContext().getResourceMap(Venda.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLCliente.setText(resourceMap.getString("jLCliente.text")); // NOI18N
        jLCliente.setName("jLCliente"); // NOI18N

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBCliente.setName("jCBCliente"); // NOI18N

        jLProdutos.setText(resourceMap.getString("jLProdutos.text")); // NOI18N
        jLProdutos.setName("jLProdutos"); // NOI18N

        jLCodigo.setText(resourceMap.getString("jLCodigo.text")); // NOI18N
        jLCodigo.setName("jLCodigo"); // NOI18N

        jTFCodigo.setText(resourceMap.getString("jTFCodigo.text")); // NOI18N
        jTFCodigo.setName("jTFCodigo"); // NOI18N

        jBBuscar.setText(resourceMap.getString("jBBuscar.text")); // NOI18N
        jBBuscar.setName("jBBuscar"); // NOI18N
        jBBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBuscarMouseClicked(evt);
            }
        });

        jLQtd.setText(resourceMap.getString("jLQtd.text")); // NOI18N
        jLQtd.setName("jLQtd"); // NOI18N

        jTFQtd.setText(resourceMap.getString("jTFQtd.text")); // NOI18N
        jTFQtd.setName("jTFQtd"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Item", "Vlr. Unitário", "Vlr. Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVenda.setName("jTVenda"); // NOI18N
        jScrollPane1.setViewportView(jTVenda);
        jTVenda.getColumnModel().getColumn(0).setResizable(false);
        jTVenda.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTVenda.columnModel.title0")); // NOI18N
        jTVenda.getColumnModel().getColumn(1).setResizable(false);
        jTVenda.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTVenda.columnModel.title1")); // NOI18N
        jTVenda.getColumnModel().getColumn(2).setResizable(false);
        jTVenda.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTVenda.columnModel.title2")); // NOI18N
        jTVenda.getColumnModel().getColumn(3).setResizable(false);
        jTVenda.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTVenda.columnModel.title3")); // NOI18N

        jBInserir.setText(resourceMap.getString("jBInserir.text")); // NOI18N
        jBInserir.setName("jBInserir"); // NOI18N

        jLTotal.setText(resourceMap.getString("jLTotal.text")); // NOI18N
        jLTotal.setName("jLTotal"); // NOI18N

        jTFTotal.setText(resourceMap.getString("jTFTotal.text")); // NOI18N
        jTFTotal.setName("jTFTotal"); // NOI18N

        jBGravar.setText(resourceMap.getString("jBGravar.text")); // NOI18N
        jBGravar.setName("jBGravar"); // NOI18N
        jBGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGravarMouseClicked(evt);
            }
        });

        jBSair.setText(resourceMap.getString("jBSair.text")); // NOI18N
        jBSair.setName("jBSair"); // NOI18N
        jBSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTFQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBBuscar)))))
                            .addComponent(jLQtd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(jBInserir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLTotal)
                                .addGap(18, 18, 18)
                                .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBGravar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jBSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCliente)
                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigo)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar)
                    .addComponent(jBInserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQtd)
                    .addComponent(jTFQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotal)
                    .addComponent(jTFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGravar)
                    .addComponent(jBSair))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBuscarMouseClicked
        Produtos produtos = new Produtos();
        produtos.setVisible(true);
    }//GEN-LAST:event_jBBuscarMouseClicked

    private void jBSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_jBSairMouseClicked

    private void jBGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGravarMouseClicked
     IncluirCredito incluirCredito = new IncluirCredito();
       /* try {
            incluirCredito.Incluir(jCBCliente.getSelectedItem());
                    //(Float.parseFloat(jtfValorItens.getText()), clientes.get((String) jcomboCliente.getSelectedItem()));
            percorreTable(in.getUltimoIDMarmita());
        } catch (NumberFormatException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_jBGravarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Venda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBInserir;
    private javax.swing.JButton jBSair;
    private javax.swing.JComboBox jCBCliente;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLProdutos;
    private javax.swing.JLabel jLQtd;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFQtd;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTable jTVenda;
    // End of variables declaration//GEN-END:variables
}
