/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Produtos.java
 *
 * Created on 30/09/2010, 20:05:42
 */

package clientewebservice;

/**
 *
 * @author leandro
 */
public class Produtos extends javax.swing.JFrame {

    /** Creates new form Produtos */
    public Produtos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPesquisar = new javax.swing.JLabel();
        jTFPesquisar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProduto = new javax.swing.JTable();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(clientewebservice.ClienteWebServiceApp.class).getContext().getResourceMap(Produtos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLPesquisar.setText(resourceMap.getString("jLPesquisar.text")); // NOI18N
        jLPesquisar.setName("jLPesquisar"); // NOI18N

        jTFPesquisar.setText(resourceMap.getString("jTFPesquisar.text")); // NOI18N
        jTFPesquisar.setName("jTFPesquisar"); // NOI18N

        jBBuscar.setText(resourceMap.getString("jBBuscar.text")); // NOI18N
        jBBuscar.setName("jBBuscar"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Valor Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProduto.setName("jTProduto"); // NOI18N
        jScrollPane1.setViewportView(jTProduto);
        jTProduto.getColumnModel().getColumn(0).setResizable(false);
        jTProduto.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTProduto.columnModel.title0")); // NOI18N
        jTProduto.getColumnModel().getColumn(1).setResizable(false);
        jTProduto.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTProduto.columnModel.title1")); // NOI18N
        jTProduto.getColumnModel().getColumn(2).setResizable(false);
        jTProduto.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTProduto.columnModel.title2")); // NOI18N

        jBSair.setText(resourceMap.getString("jBSair.text")); // NOI18N
        jBSair.setName("jBSair"); // NOI18N
        jBSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSair)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLPesquisar)
                            .addGap(18, 18, 18)
                            .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jBBuscar))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPesquisar)
                    .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSairMouseClicked
this.dispose();
    }//GEN-LAST:event_jBSairMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTable jTProduto;
    // End of variables declaration//GEN-END:variables

}
